name: build and test

on:
  push:
    branches: [main] #Run on pushes to main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest 
    steps:
      -uses: actions/checkout@v3
      -name: Install dependencies
      -name: Run tests